First I imported all the libraries needed

In [16]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA

Now data is loaded from train.csv to a pandas dataframe

In [17]:
df = pd.read_csv('train.csv')
#shape of data
df.shape

(4209, 378)

In [18]:
#basic schema of datafram can be seen using head()
df.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [19]:
df.describe()

,ID,y,X10,X11,X12,X13,X14,X15,X16,X17,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
count,4209.000000,4209.000000,4209.000000,4209.0,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,...,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000
mean,4205.960798,100.669318,0.013305,0.0,0.075077,0.057971,0.428130,0.000475,0.002613,0.007603,...,0.318841,0.057258,0.314802,0.020670,0.009503,0.008078,0.007603,0.001663,0.000475,0.001426
std,2437.608688,12.679381,0.114590,0.0,0.263547,0.233716,0.494867,0.021796,0.051061,0.086872,...,0.466082,0.232363,0.464492,0.142294,0.097033,0.089524,0.086872,0.040752,0.021796,0.037734
min,0.000000,72.110000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2095.000000,90.820000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4220.000000,99.150000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6314.000000,109.010000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,8417.000000,265.320000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

NOw we have y as output column. Next target/output column is extracted from dataframe in a separate array and then removed from dataset

In [20]:
y = df['y'].values
y

array([130.81,  88.53,  76.26, ..., 109.22,  87.48, 110.85])

Now a/c to problem statement all the features required for benchtest starts with X. So now we extract all the features necessary.

In [21]:
cols = [x for x in df.columns if 'X' in x]
print('Necessary features: {}'.format(len(cols)))
cols

Necessary features: 376

['X0',
 'X1',
 'X2',
 'X3',
 'X4',
 'X5',
 'X6',
 'X8',
 'X10',
 'X11',
 'X12',
 'X13',
 'X14',
 'X15',
 'X16',
 'X17',
 'X18',
 'X19',
 'X20',
 'X21',
 'X22',
 'X23',
 'X24',
 'X26',
 'X27',
 'X28',
 'X29',
 'X30',
 'X31',
 'X32',
 'X33',
 'X34',
 'X35',
 'X36',
 'X37',
 'X38',
 'X39',
 'X40',
 'X41',
 'X42',
 'X43',
 'X44',
 'X45',
 'X46',
 'X47',
 'X48',
 'X49',
 'X50',
 'X51',
 'X52',
 'X53',
 'X54',
 'X55',
 'X56',
 'X57',
 'X58',
 'X59',
 'X60',
 'X61',
 'X62',
 'X63',
 'X64',
 'X65',
 'X66',
 'X67',
 'X68',
 'X69',
 'X70',
 'X71',
 'X73',
 'X74',
 'X75',
 'X76',
 'X77',
 'X78',
 'X79',
 'X80',
 'X81',
 'X82',
 'X83',
 'X84',
 'X85',
 'X86',
 'X87',
 'X88',
 'X89',
 'X90',
 'X91',
 'X92',
 'X93',
 'X94',
 'X95',
 'X96',
 'X97',
 'X98',
 'X99',
 'X100',
 'X101',
 'X102',
 'X103',
 'X104',
 'X105',
 'X106',
 'X107',
 'X108',
 'X109',
 'X110',
 'X111',
 'X112',
 'X113',
 'X114',
 'X115',
 'X116',
 'X117',
 'X118',
 'X119',
 'X120',
 'X122',
 'X123',
 'X124',
 'X125',
 'X126',
 'X127',
 'X128',
 'X129',
 'X130',
 'X131',
 'X132',
 'X133',
 'X134',
 'X135',
 'X136',
 'X137',
 'X138',
 'X139',
 'X140',
 'X141',
 'X142',
 'X143',
 'X144',
 'X145',
 'X146',
 'X147',
 'X148',
 'X150',
 'X151',
 'X152',
 'X153',
 'X154',
 'X155',
 'X156',
 'X157',
 'X158',
 'X159',
 'X160',
 'X161',
 'X162',
 'X163',
 'X164',
 'X165',
 'X166',
 'X167',
 'X168',
 'X169',
 'X170',
 'X171',
 'X172',
 'X173',
 'X174',
 'X175',
 'X176',
 'X177',
 'X178',
 'X179',
 'X180',
 'X181',
 'X182',
 'X183',
 'X184',
 'X185',
 'X186',
 'X187',
 'X189',
 'X190',
 'X191',
 'X192',
 'X194',
 'X195',
 'X196',
 'X197',
 'X198',
 'X199',
 'X200',
 'X201',
 'X202',
 'X203',
 'X204',
 'X205',
 'X206',
 'X207',
 'X208',
 'X209',
 'X210',
 'X211',
 'X212',
 'X213',
 'X214',
 'X215',
 'X216',
 'X217',
 'X218',
 'X219',
 'X220',
 'X221',
 'X222',
 'X223',
 'X224',
 'X225',
 'X226',
 'X227',
 'X228',
 'X229',
 'X230',
 'X231',
 'X232',
 'X233',
 'X234',
 'X235',
 'X236',
 'X237',
 'X238',
 'X239',
 'X240',
 'X241',
 'X242',
 'X243',
 'X244',
 'X245',
 'X246',
 'X247',
 'X248',
 'X249',
 'X250',
 'X251',
 'X252',
 'X253',
 'X254',
 'X255',
 'X256',
 'X257',
 'X258',
 'X259',
 'X260',
 'X261',
 'X262',
 'X263',
 'X264',
 'X265',
 'X266',
 'X267',
 'X268',
 'X269',
 'X270',
 'X271',
 'X272',
 'X273',
 'X274',
 'X275',
 'X276',
 'X277',
 'X278',
 'X279',
 'X280',
 'X281',
 'X282',
 'X283',
 'X284',
 'X285',
 'X286',
 'X287',
 'X288',
 'X289',
 'X290',
 'X291',
 'X292',
 'X293',
 'X294',
 'X295',
 'X296',
 'X297',
 'X298',
 'X299',
 'X300',
 'X301',
 'X302',
 'X304',
 'X305',
 'X306',
 'X307',
 'X308',
 'X309',
 'X310',
 'X311',
 'X312',
 'X313',
 'X314',
 'X315',
 'X316',
 'X317',
 'X318',
 'X319',
 'X320',
 'X321',
 'X322',
 'X323',
 'X324',
 'X325',
 'X326',
 'X327',
 'X328',
 'X329',
 'X330',
 'X331',
 'X332',
 'X333',
 'X334',
 'X335',
 'X336',
 'X337',
 'X338',
 'X339',
 'X340',
 'X341',
 'X342',
 'X343',
 'X344',
 'X345',
 'X346',
 'X347',
 'X348',
 'X349',
 'X350',
 'X351',
 'X352',
 'X353',
 'X354',
 'X355',
 'X356',
 'X357',
 'X358',
 'X359',
 'X360',
 'X361',
 'X362',
 'X363',
 'X364',
 'X365',
 'X366',
 'X367',
 'X368',
 'X369',
 'X370',
 'X371',
 'X372',
 'X373',
 'X374',
 'X375',
 'X376',
 'X377',
 'X378',
 'X379',
 'X380',
 'X382',
 'X383',
 'X384',
 'X385']

Now we need to find out whether there is any feature which doesn't have numerical values & if that exists then we need to change those values into numerical ones.

In [22]:
df[cols].dtypes.value_counts()

int64     368
object      8
dtype: int64

Now data in each of the column is counted

In [ ]:
data_count_cols = [[], [], []]
for c in cols:
    typ = df[c].dtype
    uniq = len(np.unique(df[c]))
    if uniq == 1:
        data_count_cols[0].append(c)
    elif uniq == 2 and typ == np.int64:
        data_count_cols[1].append(c)
    else:
        data_count_cols[2].append(c)

In [29]:
print('Constant features: {} \nBinary features: {} \nCategorical features: {}\n'
      .format(*[len(c) for c in data_count_cols]))
print('Constant features:', data_count_cols[0])
print('Categorical features:', data_count_cols[2])

Constant features: 12
Binary features: 356
Categorical features: 8

Constant features: ['X11', 'X93', 'X107', 'X233', 'X235', 'X268', 'X289', 'X290', 'X293', 'X297', 'X330', 'X347']
Categorical features: ['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8']

Now I load test data in a pandas dataframe

In [30]:
df_test = pd.read_csv('test.csv')

# remove\ing columns ID and output data from the dataframe as they are not required in model training
usable_columns = list(set(df.columns) - set(['ID', 'y']))
y_train = df['y'].values
id_test = df_test['ID'].values

x_train = df[usable_columns]
x_test = df_test[usable_columns]

Now I perform data cleaning by running a check for null and unique values on datasets.

In [31]:
def check_missing_values(df):
    if df.isnull().any().any():
        print("There are missing values in the dataframe")
    else:
        print("There are no missing values in the dataframe")
check_missing_values(x_train)
check_missing_values(x_test)

There are no missing values in the dataframe
There are no missing values in the dataframe

Now I apply label encoding on columns and remove columns with variance equal to zero.

In [32]:
for column in usable_columns:
    cardinality = len(np.unique(x_train[column]))
    if cardinality == 1:
        x_train.drop(column, axis=1) # all the columns with only one value is dropped
        x_test.drop(column, axis=1)
    if cardinality > 2: # categorical column check
        mapper = lambda x: sum([ord(digit) for digit in x])
        x_train[column] = x_train[column].apply(mapper)
        x_test[column] = x_test[column].apply(mapper)
x_train.head()

<ipython-input-32-45ca6bde81ce>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[column] = x_train[column].apply(mapper)
<ipython-input-32-45ca6bde81ce>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test[column] = x_test[column].apply(mapper)

,X369,X62,X280,X184,X83,X248,X307,X119,X2,X242,...,X97,X85,X43,X33,X362,X237,X363,X368,X265,X134
0,0,0,0,1,0,0,0,1,213,0,...,0,1,0,0,0,1,0,0,0,0
1,0,0,0,0,0,0,0,1,215,0,...,0,1,0,0,0,0,1,0,1,0
2,0,0,0,0,0,0,0,0,110,0,...,0,1,1,0,0,0,1,0,0,0
3,0,0,0,0,0,0,0,0,110,0,...,0,0,1,0,0,0,1,0,0,0
4,0,0,0,0,0,0,0,0,110,0,...,0,0,1,0,0,0,1,0,0,0

In [33]:
# checking the data type for numerical values

print('Feature types:')
x_train[cols].dtypes.value_counts()

Feature types:

int64    376
dtype: int64

applied PCA for linear dimensionality reduction

In [36]:
n_comp = 12
pca = PCA(n_components=n_comp, random_state=420)
pca2_results_train = pca.fit_transform(x_train)
pca2_results_test = pca.transform(x_test)

Initialising xgboost

In [41]:
import xgboost as xgb
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

x_train, x_valid, y_train, y_valid = train_test_split(
        pca2_results_train, 
        y_train, test_size=0.2, 
        random_state=4242)

d_train = xgb.DMatrix(x_train, label=y_train)
d_valid = xgb.DMatrix(x_valid, label=y_valid)

d_test = xgb.DMatrix(pca2_results_test)

In [42]:
params = {}
params['objective'] = 'reg:linear'
params['eta'] = 0.02
params['max_depth'] = 4

def xgb_r2_score(preds, dtrain):
    labels = dtrain.get_label()
    return 'r2', r2_score(labels, preds)

watchlist = [(d_train, 'train'), (d_valid, 'valid')]

clf = xgb.train(params, d_train, 
                1000, watchlist, early_stopping_rounds=50, 
                feval=xgb_r2_score, maximize=True, verbose_eval=10)

[21:54:09] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/objective/regression_obj.cu:171: reg:linear is now deprecated in favor of reg:squarederror.
[0]	train-rmse:99.14835	train-r2:-58.35295	valid-rmse:98.26297	valid-r2:-67.63754
[10]	train-rmse:81.27653	train-r2:-38.88428	valid-rmse:80.36433	valid-r2:-44.91014
[20]	train-rmse:66.71610	train-r2:-25.87403	valid-rmse:65.77334	valid-r2:-29.75260
[30]	train-rmse:54.86912	train-r2:-17.17722	valid-rmse:53.89136	valid-r2:-19.64525
[40]	train-rmse:45.24710	train-r2:-11.36097	valid-rmse:44.22323	valid-r2:-12.90218
[50]	train-rmse:37.44854	train-r2:-7.46723	valid-rmse:36.37614	valid-r2:-8.40622
[60]	train-rmse:31.14584	train-r2:-4.85695	valid-rmse:30.02252	valid-r2:-5.40732
[70]	train-rmse:26.08417	train-r2:-3.10795	valid-rmse:24.91497	valid-r2:-3.41268
[80]	train-rmse:22.04313	train-r2:-1.93371	valid-rmse:20.83055	valid-r2:-2.08449
[90]	train-rmse:18.84671	train-r2:-1.14458	valid-rmse:17.59679	valid-r2:-1.20115
[100]	train-rmse:16.33279	train-r2:-0.61062	valid-rmse:15.07888	valid-r2:-0.61629
[110]	train-rmse:14.39755	train-r2:-0.25155	valid-rmse:13.14822	valid-r2:-0.22890
[120]	train-rmse:12.92783	train-r2:-0.00907	valid-rmse:11.69290	valid-r2:0.02809
[130]	train-rmse:11.80680	train-r2:0.15834	valid-rmse:10.61692	valid-r2:0.19873
[140]	train-rmse:10.98472	train-r2:0.27147	valid-rmse:9.85685	valid-r2:0.30935
[150]	train-rmse:10.37312	train-r2:0.35033	valid-rmse:9.32088	valid-r2:0.38242
[160]	train-rmse:9.91865	train-r2:0.40601	valid-rmse:8.95927	valid-r2:0.42940
[170]	train-rmse:9.58084	train-r2:0.44578	valid-rmse:8.71328	valid-r2:0.46031
[180]	train-rmse:9.33902	train-r2:0.47341	valid-rmse:8.55257	valid-r2:0.48003
[190]	train-rmse:9.15109	train-r2:0.49439	valid-rmse:8.44777	valid-r2:0.49270
[200]	train-rmse:9.00817	train-r2:0.51006	valid-rmse:8.38791	valid-r2:0.49986
[210]	train-rmse:8.90467	train-r2:0.52125	valid-rmse:8.34975	valid-r2:0.50440
[220]	train-rmse:8.82894	train-r2:0.52936	valid-rmse:8.31976	valid-r2:0.50796
[230]	train-rmse:8.76702	train-r2:0.53594	valid-rmse:8.30397	valid-r2:0.50982
[240]	train-rmse:8.72161	train-r2:0.54073	valid-rmse:8.29916	valid-r2:0.51039
[250]	train-rmse:8.67967	train-r2:0.54514	valid-rmse:8.29209	valid-r2:0.51122
[260]	train-rmse:8.64575	train-r2:0.54869	valid-rmse:8.28976	valid-r2:0.51150
[270]	train-rmse:8.61264	train-r2:0.55214	valid-rmse:8.28928	valid-r2:0.51155
[280]	train-rmse:8.57794	train-r2:0.55574	valid-rmse:8.28786	valid-r2:0.51172
[290]	train-rmse:8.55248	train-r2:0.55837	valid-rmse:8.28645	valid-r2:0.51189
[300]	train-rmse:8.52479	train-r2:0.56123	valid-rmse:8.28302	valid-r2:0.51229
[310]	train-rmse:8.49976	train-r2:0.56380	valid-rmse:8.28059	valid-r2:0.51258
[320]	train-rmse:8.47695	train-r2:0.56614	valid-rmse:8.28008	valid-r2:0.51264
[330]	train-rmse:8.45091	train-r2:0.56880	valid-rmse:8.27434	valid-r2:0.51331
[340]	train-rmse:8.42872	train-r2:0.57106	valid-rmse:8.27659	valid-r2:0.51305
[350]	train-rmse:8.40710	train-r2:0.57326	valid-rmse:8.27322	valid-r2:0.51345
[360]	train-rmse:8.38170	train-r2:0.57583	valid-rmse:8.27188	valid-r2:0.51360
[370]	train-rmse:8.35697	train-r2:0.57833	valid-rmse:8.27089	valid-r2:0.51372
[380]	train-rmse:8.33311	train-r2:0.58074	valid-rmse:8.26987	valid-r2:0.51384
[390]	train-rmse:8.31093	train-r2:0.58297	valid-rmse:8.27063	valid-r2:0.51375
[400]	train-rmse:8.28275	train-r2:0.58579	valid-rmse:8.26831	valid-r2:0.51402
[410]	train-rmse:8.25841	train-r2:0.58822	valid-rmse:8.26712	valid-r2:0.51416
[420]	train-rmse:8.23559	train-r2:0.59049	valid-rmse:8.26757	valid-r2:0.51411
[430]	train-rmse:8.20573	train-r2:0.59346	valid-rmse:8.26489	valid-r2:0.51443
[440]	train-rmse:8.17858	train-r2:0.59614	valid-rmse:8.26434	valid-r2:0.51449
[450]	train-rmse:8.15284	train-r2:0.59868	valid-rmse:8.26204	valid-r2:0.51476
[460]	train-rmse:8.12942	train-r2:0.60098	valid-rmse:8.26338	valid-r2:0.51460
[470]	train-rmse:8.10067	train-r2:0.60380	valid-rmse:8.26070	valid-r2:0.51492
[480]	train-rmse:8.07698	train-r2:0.60611	valid-rmse:8.26236	valid-r2:0.51472
[490]	train-rmse:8.05630	train-r2:0.60813	valid-rmse:8.26142	valid-r2:0.51483
[500]	train-rmse:8.02587	train-r2:0.61108	valid-rmse:8.26353	valid-r2:0.51458
[510]	train-rmse:8.00192	train-r2:0.61340	valid-rmse:8.26271	valid-r2:0.51468
[520]	train-rmse:7.97685	train-r2:0.61582	valid-rmse:8.26362	valid-r2:0.51458
[522]	train-rmse:7.97326	train-r2:0.61617	valid-rmse:8.26334	valid-r2:0.51461

In [44]:
#finally predicting the test dataframe values using xgboost

p_test = clf.predict(d_test)
p_test

array([ 83.050865,  97.10839 ,  83.02353 , ...,  98.948265, 106.92117 ,
        96.70014 ], dtype=float32)